services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: rechnungdb
      POSTGRES_USER: rechnung
      POSTGRES_PASSWORD: geheim123!
    ports:
      - "8083:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8084:80"
    depends_on:
      - db
volumes:
  pgdata: